# The URL the site will be built for
base_url = "https://blog.krx.sh"
title = "//TODO(rose)"
theme = "pizza"

compile_sass = true
build_search_index = false
minify_html = true

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
